/**
 * /blog/week-1 — first public weekly narrative, running GRID on GRID.
 *
 * Published at a permanent slug (week-1) rather than a title so the
 * auto-post cron lands every subsequent week at /blog/week-2,
 * /blog/week-3, etc. Each week's narrative is a short memo; the
 * cadence compounds into the public build log.
 */

import type { Metadata } from 'next';
import Link from 'next/link';
import LegalFooter from '@/components/LegalFooter';

export const metadata: Metadata = {
  title: 'Week 1 — what GRID shipped · Blog',
  description:
    'The first public weekly narrative. GRID runs on GRID; every Monday the Environment page writes a memo like this one. We are posting ours publicly because the product thesis is that work should be legible.',
};

export default function Week1Page() {
  return (
    <div className="min-h-screen ambient-bg">
      <div className="max-w-3xl mx-auto px-5 md:px-8 py-20 md:py-28">
        <Link
          href="/blog"
          className="inline-flex items-center gap-2 text-xs font-light mb-12 transition-colors hover:text-white/60"
          style={{ color: 'var(--text-3)' }}
        >
          <span>&larr;</span> Blog
        </Link>

        <p
          className="text-[10px] tracking-[0.18em] uppercase mb-3 font-light"
          style={{ color: 'var(--brand)', opacity: 0.8 }}
        >
          Week 1 · Build in public
        </p>
        <h1
          className="text-3xl md:text-5xl font-extralight tracking-tight leading-[1.1] mb-4"
          style={{ letterSpacing: '-0.02em' }}
        >
          What GRID shipped, in one memo
        </h1>
        <p className="text-sm font-light mb-12" style={{ color: 'var(--text-3)' }}>
          Generated by Nova from 7 days of AuditLog, IntelligenceLog, and Goal deltas
          on GRID&rsquo;s own Environment. Same format every Monday, forever.
        </p>

        <article className="space-y-6 blog-prose" style={{ color: 'var(--text-2)' }}>
          <section>
            <p
              className="text-[10px] tracking-[0.16em] uppercase mb-2 font-light"
              style={{ color: 'var(--text-3)' }}
            >
              The thesis
            </p>
            <p>
              Every company has three AI problems nobody sells a cure for. People
              sabotage rollouts they don&rsquo;t trust. CFOs can&rsquo;t tell if any
              of it is working. New users don&rsquo;t know what they want.
            </p>
            <p>
              We think the cure is a <strong>substrate</strong> — something that
              reads your company, acts with your permission, and proves its
              work. Not a dashboard. Not a chatbot. Not another workflow builder.
              Something underneath all three.
            </p>
          </section>

          <section>
            <p
              className="text-[10px] tracking-[0.16em] uppercase mb-2 font-light"
              style={{ color: 'var(--text-3)' }}
            >
              What shipped this week
            </p>
            <ul>
              <li>
                <strong>Meetings on the calendar.</strong> Native Meeting model,
                Task/Meeting switcher in the quick-add, pink pills on the month
                view, Event drawer with Google / Outlook / <code>.ics</code> export.
                Meetings are the last thing still in a separate tool for most teams;
                we brought them inside.
              </li>
              <li>
                <strong>Team invitations end to end.</strong> EnvironmentInvitation
                model, token-hashed email invites via Resend, accept flow that
                routes through sign-up for new users. Roles: Owner, Admin,
                Contributor, Viewer.
              </li>
              <li>
                <strong>Environments, editable and deletable everywhere.</strong>
                Rename and delete inline on the list, in the detail header, in the
                sidebar. Deleting an Environment cascades: its Systems and Workflows
                vanish from every surface live, not on next page load.
              </li>
              <li>
                <strong>Documents, properly deletable.</strong> Replaced emoji icons
                with brand-colored circles keyed to the document&rsquo;s environment.
                Switched the delete API from soft-archive to a real hard delete
                with cascading children.
              </li>
              <li>
                <strong>Department surface catalog.</strong> A typed preset list per
                department (Brand, Marketing, Operations, Finance, Design,
                Development, General) with recommended defaults. Each preset is
                toggleable — user picks what shows on their Environment page.
              </li>
              <li>
                <strong>Hideable panels on the System page.</strong> Every right-rail
                panel can be hidden with a hover &times; and restored from the chip
                at the top.
              </li>
              <li>
                <strong>Trust primitives made visible.</strong> WhyDrawer on every
                Nova action (read + reasoning + tokens + cost), 24-hour reversible
                undo window, teach-Nova override capture. All in one click from the
                action ledger.
              </li>
              <li>
                <strong>Interaction layer.</strong> A prompt like &ldquo;Design a Meta
                ad campaign with Canva creative&rdquo; now plans a 6-step project
                across Notion, Claude, Canva, a human gate, Meta Ads, and Gmail —
                with real writes, not stubs.
              </li>
            </ul>
          </section>

          <section>
            <p
              className="text-[10px] tracking-[0.16em] uppercase mb-2 font-light"
              style={{ color: 'var(--text-3)' }}
            >
              What we believe now that we didn&rsquo;t at the start of the week
            </p>
            <ul>
              <li>
                <strong>Live sync across surfaces is the foundation, not a polish
                pass.</strong> Every sabotage story we heard from early users traced
                back to &ldquo;I deleted it and it kept showing up.&rdquo; Invisible
                deletes break trust in a way no onboarding flow can recover.
              </li>
              <li>
                <strong>Dept-native presets matter more than a universal
                template.</strong> Finance people do not want the marketing surface
                with the colors changed. Same substrate, six viewing angles, is the
                correct shape.
              </li>
              <li>
                <strong>Removability is as important as configurability.</strong> A
                Finance lead who hides the &ldquo;content engine&rdquo; panel trusts
                the tool more than one who is told to ignore it.
              </li>
            </ul>
          </section>

          <section>
            <p
              className="text-[10px] tracking-[0.16em] uppercase mb-2 font-light"
              style={{ color: 'var(--text-3)' }}
            >
              What we are working on next
            </p>
            <ul>
              <li>
                <strong>The Environment page as the canonical artifact.</strong> One
                honest headline number, an exceptions feed, a Nova-written Monday
                narrative, and a live action ledger. Screenshot-worthy by design.
                (Shipped; next pass: polish + tighter spacing.)
              </li>
              <li>
                <strong>Onboarding becomes an interview, not a prompt.</strong> Five
                questions, then Nova proposes the Systems, Goals, and Workflows it
                heard. The blank-page problem is the biggest activation failure in
                AI products; we&rsquo;re killing it. (Shipped.)
              </li>
              <li>
                <strong>Real SSO.</strong> Every enterprise conversation currently
                stalls on &ldquo;Can my team sign in with Google?&rdquo; — unblock it.
                (Next up.)
              </li>
              <li>
                <strong>Public weekly narrative auto-post.</strong> Run GRID on GRID.
                Monday narrative generates, posts to <code>/blog/week-N</code>{' '}
                automatically. This post is week 1; everything after publishes
                itself.
              </li>
            </ul>
          </section>

          <section>
            <p
              className="text-[10px] tracking-[0.16em] uppercase mb-2 font-light"
              style={{ color: 'var(--text-3)' }}
            >
              The artifact
            </p>
            <p>
              If you want to see what a workspace that acts looks like, the
              product is live. Request access below and run your own Monday
              narrative next week.
            </p>
          </section>
        </article>

        <div
          className="rounded-2xl p-6 mt-12 mb-6"
          style={{ background: 'var(--glass)', border: '1px solid var(--glass-border)' }}
        >
          <p
            className="text-[10px] tracking-[0.18em] uppercase mb-2 font-light"
            style={{ color: 'var(--brand)' }}
          >
            Weekly cadence, forever
          </p>
          <p className="text-sm font-light leading-relaxed" style={{ color: 'var(--text-2)' }}>
            Same format, same page structure, different content. Every Monday. The
            weekly narrative is the product; publishing it publicly is how the
            product sells itself.
          </p>
        </div>

        <p className="text-[11px] font-light" style={{ color: 'var(--text-3)' }}>
          <Link href="/#waitlist" style={{ color: 'var(--brand)' }}>Request access</Link>
          {' · '}
          <Link href="/capabilities" style={{ color: 'var(--brand)' }}>See what's wired</Link>
          {' · '}
          <Link href="/roadmap" style={{ color: 'var(--brand)' }}>Roadmap</Link>
        </p>
      </div>
      <style>{`
        .blog-prose p { margin-bottom: 0.75rem; line-height: 1.7; }
        .blog-prose ul { list-style: disc; padding-left: 1.25rem; margin: 0.75rem 0; line-height: 1.7; }
        .blog-prose li { margin-bottom: 0.6rem; }
        .blog-prose strong { color: var(--text-1); font-weight: 400; }
        .blog-prose code {
          font-size: 0.8em;
          background: rgba(255,255,255,0.04);
          padding: 1px 5px;
          border-radius: 4px;
        }
      `}</style>
      <LegalFooter />
    </div>
  );
}
