/**
 * Content Loop — "Ideas die between draft and publish"
 *
 * Manual trigger. Takes a rough idea → research angle → draft →
 * self-critique → final. The self-critique stage is the key: we pass
 * the draft back through the kernel with a separate critic persona,
 * then fold the critique into the rewrite. This is RLAIF-lite —
 * feedback is generated by the same family of model but routed to a
 * different tier for cheap, honest criticism.
 */
export const contentLoopTemplate = {
  schemaVersion: 1 as const,
  slug: 'content-loop',
  name: 'Content loop',
  tagline: 'Idea in, publish-ready piece out — with a self-critic in the middle.',
  description:
    'Turns a one-line idea into a drafted, self-critiqued, rewritten piece. The critic pass uses a separate persona so the final output is sharper than any single-shot generation.',
  version: '1.0.0',
  category: 'content' as const,
  tags: ['content', 'draft', 'self-critique', 'rlaif'],
  trigger: {
    type: 'manual' as const,
  },
  inputSchema: {
    description: 'A one-line idea for a post, essay, or announcement.',
    example: 'Why remote teams should kill the weekly all-hands',
  },
  stages: [
    {
      id: 'angle',
      name: 'Find angle',
      description: 'Pick the sharpest angle for the idea.',
      instruction:
        'Raw idea: ${input}\n\n' +
        'Propose the three sharpest possible angles for this piece. ' +
        'For each angle: the thesis in one sentence, the audience, and the "so what". ' +
        'End by picking the strongest angle with a one-line justification.',
      dependsOn: [],
      tools: [],
      tier: 'balanced' as const,
      maxTokens: 700,
      critical: true,
      requiresApproval: false,
    },
    {
      id: 'draft',
      name: 'Draft v1',
      description: 'Write the first draft.',
      instruction:
        'Chosen angle and thesis:\n\n${stages.angle.output}\n\n' +
        'Write a first draft of the piece. 400–600 words. Hook → argument → evidence → payoff. ' +
        'Voice: confident, specific, no hedging. No intro paragraph about how "in today\'s world".',
      dependsOn: ['angle'],
      tools: [],
      tier: 'balanced' as const,
      maxTokens: 1500,
      critical: true,
      requiresApproval: false,
    },
    {
      id: 'critique',
      name: 'Self-critique',
      description: 'Harsh editor pass on the draft.',
      instruction:
        'You are a harsh editor. Here is a draft you did NOT write.\n\n' +
        '---\n${stages.draft.output}\n---\n\n' +
        'Give ruthless feedback. List exactly: ' +
        '(a) the 3 weakest sentences and why, ' +
        '(b) the 1 missing argument the piece needs, ' +
        '(c) the 1 cliché to kill, ' +
        '(d) the best sentence in the piece (so the author knows what is working).',
      dependsOn: ['draft'],
      tools: [],
      tier: 'deep' as const,
      maxTokens: 1000,
      critical: true,
      requiresApproval: false,
    },
    {
      id: 'rewrite',
      name: 'Rewrite',
      description: 'Final version incorporating the critique.',
      instruction:
        'Original draft:\n${stages.draft.output}\n\n' +
        'Editor critique:\n${stages.critique.output}\n\n' +
        'Produce the final version. Apply every critique except the ones that would make the piece worse. ' +
        'Keep the best sentence identified by the editor. 400–600 words. Ship-ready.',
      dependsOn: ['draft', 'critique'],
      tools: [],
      tier: 'deep' as const,
      maxTokens: 1500,
      critical: true,
      requiresApproval: true,
    },
  ],
};
