/**
 * Integration registry — the canonical list of every third-party
 * provider Grid can connect to, plus the metadata the UI and router
 * need to drive the connect flow.
 *
 * The registry is the single source of truth. `provider` strings
 * stored on the Integration model MUST match an id in PROVIDERS.
 * Adding a new integration means:
 *   1. Add an entry here (metadata only).
 *   2. Implement its auth flow under lib/integrations/oauth/<id>.ts
 *      or lib/integrations/apikey/<id>.ts.
 *   3. Implement its read client under lib/integrations/clients/<id>.ts.
 *   4. Wire any envEnv-var requirements into docs/INTEGRATIONS_SETUP.md.
 *
 * We intentionally keep THIS file dependency-free (no Node APIs, no
 * Prisma, no SDKs) so the React integrations page can import it for
 * the provider grid without pulling server-only modules into the
 * client bundle.
 */

export type IntegrationCategory =
  | 'advertising'
  | 'ai'
  | 'analytics'
  | 'automation'
  | 'calendar'
  | 'cloud_storage'
  | 'commerce'
  | 'comms'
  | 'crm'
  | 'database'
  | 'design'
  | 'devtools'
  | 'email_marketing'
  | 'finance'
  | 'forms'
  | 'hr'
  | 'infra'
  | 'pm'
  | 'productivity'
  | 'social'
  | 'support'
  | 'video';

export type IntegrationAuthType = 'oauth' | 'api_key' | 'service_account';

export type IntegrationProviderDef = {
  id: string; // canonical slug stored on Integration.provider
  name: string;
  tagline: string;
  category: IntegrationCategory;
  authType: IntegrationAuthType;

  // Display-only. Not used for auth — just for the provider grid.
  accentColor: string;

  // OAuth providers declare their scopes; api_key providers leave []
  scopes: string[];

  // For api_key providers: the shape of the form the UI renders.
  // Each field becomes a named input on the connect modal and ends up
  // in the credential blob as { [field]: value } JSON (then AES-GCM
  // encrypted). OAuth providers leave this empty.
  apiKeyFields?: { name: string; label: string; type: 'text' | 'password'; placeholder?: string; helper?: string }[];

  // Env vars the operator must set before this provider will work.
  // Surfaced in /api/integrations/providers so the UI can grey out
  // providers that aren't wired up yet and explain why.
  requiredEnvVars: string[];

  // Lit when at least one implemented path (auth flow + client) is
  // present. Providers that only exist in the registry but haven't
  // been coded yet set this to false → UI shows "Coming soon".
  implemented: boolean;

  // Stable single-character / short glyph for the grid card. We draw
  // our own icons rather than hotlinking vendor logos to avoid brand
  // usage issues. Keeps the interface visually cohesive with the rest
  // of the app's minimal chrome aesthetic.
  glyph: string;
};

export const CATEGORY_LABELS: Record<IntegrationCategory, string> = {
  advertising: 'Advertising',
  ai: 'AI',
  analytics: 'Analytics',
  automation: 'Automation',
  calendar: 'Calendar',
  cloud_storage: 'Cloud Storage',
  commerce: 'Commerce',
  comms: 'Communication',
  crm: 'CRM',
  database: 'Database',
  design: 'Design',
  devtools: 'Developer',
  email_marketing: 'Email Marketing',
  finance: 'Finance',
  forms: 'Forms',
  hr: 'HR',
  infra: 'Infrastructure',
  pm: 'Project Management',
  productivity: 'Productivity',
  social: 'Social Media',
  support: 'Support',
  video: 'Video',
};

export const CATEGORY_ORDER: IntegrationCategory[] = [
  'productivity',
  'pm',
  'comms',
  'calendar',
  'crm',
  'commerce',
  'email_marketing',
  'social',
  'advertising',
  'analytics',
  'design',
  'cloud_storage',
  'forms',
  'support',
  'finance',
  'hr',
  'ai',
  'automation',
  'devtools',
  'database',
  'video',
  'infra',
];

/**
 * The canonical provider list. When you add one here, the UI picks
 * it up automatically on next reload — no hand-wiring.
 */
export const PROVIDERS: IntegrationProviderDef[] = [

  // ── Productivity ────────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    tagline: 'Pages, databases, docs',
    category: 'productivity',
    authType: 'oauth',
    accentColor: '#000000',
    scopes: [],
    requiredEnvVars: ['NOTION_CLIENT_ID', 'NOTION_CLIENT_SECRET'],
    implemented: true,
    glyph: '◌',
  },
  {
    id: 'google_workspace',
    name: 'Google Workspace',
    tagline: 'Gmail, Calendar, Drive, Docs',
    category: 'productivity',
    authType: 'oauth',
    accentColor: '#4285f4',
    scopes: [
      'openid',
      'email',
      'profile',
      'https://www.googleapis.com/auth/gmail.readonly',
      'https://www.googleapis.com/auth/calendar.readonly',
      'https://www.googleapis.com/auth/drive.readonly',
    ],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '◯',
  },
  {
    id: 'figma',
    name: 'Figma',
    tagline: 'Designs, components, styles, content',
    category: 'productivity',
    authType: 'oauth',
    accentColor: '#1abcfe',
    scopes: ['files:read'],
    requiredEnvVars: ['FIGMA_CLIENT_ID', 'FIGMA_CLIENT_SECRET'],
    implemented: true,
    glyph: '◆',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    tagline: 'Bases, tables, records, views',
    category: 'productivity',
    authType: 'oauth',
    accentColor: '#18bfff',
    scopes: ['data.records:read', 'data.records:write', 'schema.bases:read'],
    requiredEnvVars: ['AIRTABLE_CLIENT_ID', 'AIRTABLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊞',
  },
  {
    id: 'confluence',
    name: 'Confluence',
    tagline: 'Wiki pages, spaces, team docs',
    category: 'productivity',
    authType: 'oauth',
    accentColor: '#1868db',
    scopes: ['read:confluence-content.all', 'read:confluence-space.summary'],
    requiredEnvVars: ['ATLASSIAN_CLIENT_ID', 'ATLASSIAN_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊡',
  },
  {
    id: 'coda',
    name: 'Coda',
    tagline: 'Docs, tables, automations',
    category: 'productivity',
    authType: 'api_key',
    accentColor: '#f46a54',
    scopes: [],
    apiKeyFields: [
      { name: 'apiToken', label: 'API token', type: 'password', placeholder: 'Coda API token', helper: 'Account settings → API tokens' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊟',
  },

  // ── Project Management ──────────────────────────────────────────
  {
    id: 'jira',
    name: 'Jira',
    tagline: 'Issues, sprints, boards, epics',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#0052cc',
    scopes: ['read:jira-work', 'read:jira-user'],
    requiredEnvVars: ['ATLASSIAN_CLIENT_ID', 'ATLASSIAN_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬡',
  },
  {
    id: 'asana',
    name: 'Asana',
    tagline: 'Tasks, projects, timelines',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#f06a6a',
    scopes: ['default'],
    requiredEnvVars: ['ASANA_CLIENT_ID', 'ASANA_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬢',
  },
  {
    id: 'linear',
    name: 'Linear',
    tagline: 'Issues, cycles, projects',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#5e6ad2',
    scopes: ['read', 'write'],
    requiredEnvVars: ['LINEAR_CLIENT_ID', 'LINEAR_CLIENT_SECRET'],
    implemented: true,
    glyph: '◍',
  },
  {
    id: 'trello',
    name: 'Trello',
    tagline: 'Boards, lists, cards',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#0079bf',
    scopes: ['read', 'write'],
    requiredEnvVars: ['TRELLO_API_KEY', 'TRELLO_API_SECRET'],
    implemented: true,
    glyph: '▦',
  },
  {
    id: 'monday',
    name: 'Monday.com',
    tagline: 'Boards, items, workflows',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#ff3d57',
    scopes: ['boards:read', 'workspaces:read'],
    requiredEnvVars: ['MONDAY_CLIENT_ID', 'MONDAY_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬣',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    tagline: 'Tasks, docs, goals, whiteboards',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#7b68ee',
    scopes: [],
    requiredEnvVars: ['CLICKUP_CLIENT_ID', 'CLICKUP_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬠',
  },
  {
    id: 'basecamp',
    name: 'Basecamp',
    tagline: 'Projects, to-dos, messages',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#1d2d35',
    scopes: [],
    requiredEnvVars: ['BASECAMP_CLIENT_ID', 'BASECAMP_CLIENT_SECRET'],
    implemented: true,
    glyph: '△',
  },
  {
    id: 'wrike',
    name: 'Wrike',
    tagline: 'Projects, tasks, Gantt charts',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#08cf65',
    scopes: ['wsReadOnly'],
    requiredEnvVars: ['WRIKE_CLIENT_ID', 'WRIKE_CLIENT_SECRET'],
    implemented: true,
    glyph: '▽',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    tagline: 'Tasks, projects, labels',
    category: 'pm',
    authType: 'oauth',
    accentColor: '#e44332',
    scopes: ['data:read', 'data:read_write'],
    requiredEnvVars: ['TODOIST_CLIENT_ID', 'TODOIST_CLIENT_SECRET'],
    implemented: true,
    glyph: '☑',
  },

  // ── Communication ───────────────────────────────────────────────
  {
    id: 'slack',
    name: 'Slack',
    tagline: 'Channels, messages, alerts',
    category: 'comms',
    authType: 'oauth',
    accentColor: '#4a154b',
    scopes: ['channels:read', 'chat:write', 'users:read'],
    requiredEnvVars: ['SLACK_CLIENT_ID', 'SLACK_CLIENT_SECRET'],
    implemented: true,
    glyph: '◉',
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    tagline: 'Channels, chats, meetings',
    category: 'comms',
    authType: 'oauth',
    accentColor: '#6264a7',
    scopes: ['Channel.ReadBasic.All', 'Chat.Read', 'User.Read'],
    requiredEnvVars: ['MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊕',
  },
  {
    id: 'discord',
    name: 'Discord',
    tagline: 'Servers, channels, bots',
    category: 'comms',
    authType: 'oauth',
    accentColor: '#5865f2',
    scopes: ['identify', 'guilds'],
    requiredEnvVars: ['DISCORD_CLIENT_ID', 'DISCORD_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊗',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    tagline: 'Meetings, webinars, recordings',
    category: 'comms',
    authType: 'oauth',
    accentColor: '#2d8cff',
    scopes: ['meeting:read', 'user:read'],
    requiredEnvVars: ['ZOOM_CLIENT_ID', 'ZOOM_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊘',
  },
  {
    id: 'twilio',
    name: 'Twilio',
    tagline: 'SMS, voice, messaging APIs',
    category: 'comms',
    authType: 'api_key',
    accentColor: '#f22f46',
    scopes: [],
    apiKeyFields: [
      { name: 'accountSid', label: 'Account SID', type: 'text', placeholder: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' },
      { name: 'authToken', label: 'Auth token', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊙',
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    tagline: 'Transactional & marketing email',
    category: 'comms',
    authType: 'api_key',
    accentColor: '#1a82e2',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', placeholder: 'SG.xxxxxx', helper: 'Settings → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '✉',
  },

  // ── Calendar ────────────────────────────────────────────────────
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    tagline: 'Events, meetings, availability',
    category: 'calendar',
    authType: 'oauth',
    accentColor: '#4285f4',
    scopes: [
      // openid/email/profile are required so the OAuth callback can
      // resolve userinfo.email — without them the integration saves
      // as "Google Calendar · undefined" because the fallback display
      // name interpolates a missing email.
      'openid',
      'email',
      'profile',
      'https://www.googleapis.com/auth/calendar.readonly',
      'https://www.googleapis.com/auth/calendar.events.readonly',
    ],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '◰',
  },
  {
    id: 'microsoft_outlook',
    name: 'Microsoft Outlook',
    tagline: 'Outlook Calendar, Teams meetings',
    category: 'calendar',
    authType: 'oauth',
    accentColor: '#0078d4',
    scopes: ['Calendars.Read', 'User.Read'],
    requiredEnvVars: ['MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET'],
    implemented: true,
    glyph: '◲',
  },
  {
    id: 'apple_calendar',
    name: 'Apple Calendar',
    tagline: 'iCloud Calendar via CalDAV',
    category: 'calendar',
    authType: 'api_key',
    accentColor: '#333333',
    scopes: [],
    apiKeyFields: [
      { name: 'appleId', label: 'Apple ID', type: 'text', placeholder: 'you@icloud.com' },
      { name: 'appPassword', label: 'App-specific password', type: 'password', placeholder: 'xxxx-xxxx-xxxx-xxxx', helper: 'Generate at appleid.apple.com > Security > App-Specific Passwords.' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◳',
  },
  {
    id: 'caldav',
    name: 'CalDAV',
    tagline: 'Any CalDAV-compatible calendar server',
    category: 'calendar',
    authType: 'api_key',
    accentColor: '#6b7280',
    scopes: [],
    apiKeyFields: [
      { name: 'serverUrl', label: 'CalDAV server URL', type: 'text', placeholder: 'https://caldav.example.com/dav/' },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user@example.com' },
      { name: 'password', label: 'Password', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◱',
  },
  {
    id: 'calendly',
    name: 'Calendly',
    tagline: 'Scheduling, event types, bookings',
    category: 'calendar',
    authType: 'oauth',
    accentColor: '#006bff',
    scopes: [],
    requiredEnvVars: ['CALENDLY_CLIENT_ID', 'CALENDLY_CLIENT_SECRET'],
    implemented: true,
    glyph: '◫',
  },

  // ── CRM ─────────────────────────────────────────────────────────
  {
    id: 'salesforce',
    name: 'Salesforce',
    tagline: 'Opportunities, pipeline, activities',
    category: 'crm',
    authType: 'oauth',
    accentColor: '#00a1e0',
    scopes: ['api', 'refresh_token'],
    requiredEnvVars: ['SALESFORCE_CLIENT_ID', 'SALESFORCE_CLIENT_SECRET'],
    implemented: true,
    glyph: '◕',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    tagline: 'Contacts, deals, marketing',
    category: 'crm',
    authType: 'oauth',
    accentColor: '#ff7a59',
    scopes: ['crm.objects.contacts.read', 'crm.objects.deals.read'],
    requiredEnvVars: ['HUBSPOT_CLIENT_ID', 'HUBSPOT_CLIENT_SECRET'],
    implemented: true,
    glyph: '◖',
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    tagline: 'Deals, contacts, activities',
    category: 'crm',
    authType: 'oauth',
    accentColor: '#017737',
    scopes: [],
    requiredEnvVars: ['PIPEDRIVE_CLIENT_ID', 'PIPEDRIVE_CLIENT_SECRET'],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◗',
  },
  {
    id: 'zoho_crm',
    name: 'Zoho CRM',
    tagline: 'Leads, deals, accounts, contacts',
    category: 'crm',
    authType: 'oauth',
    accentColor: '#e42527',
    scopes: ['ZohoCRM.modules.ALL'],
    requiredEnvVars: ['ZOHO_CLIENT_ID', 'ZOHO_CLIENT_SECRET'],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◑',
  },
  {
    id: 'freshsales',
    name: 'Freshsales',
    tagline: 'Contacts, deals, sales sequences',
    category: 'crm',
    authType: 'api_key',
    accentColor: '#13b981',
    scopes: [],
    apiKeyFields: [
      { name: 'domain', label: 'Domain', type: 'text', placeholder: 'acme.freshsales.io' },
      { name: 'apiKey', label: 'API key', type: 'password', helper: 'Settings → API Settings' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◒',
  },
  {
    id: 'close',
    name: 'Close',
    tagline: 'Leads, opportunities, calls',
    category: 'crm',
    authType: 'api_key',
    accentColor: '#2b2d42',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', placeholder: 'api_xxxxxx', helper: 'Settings → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◓',
  },

  // ── Commerce ────────────────────────────────────────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    tagline: 'Revenue, subscriptions, churn',
    category: 'commerce',
    authType: 'api_key',
    accentColor: '#635bff',
    scopes: [],
    apiKeyFields: [
      {
        name: 'secretKey',
        label: 'Secret key',
        type: 'password',
        placeholder: 'sk_live_…',
        helper: 'Dashboard → Developers → API keys. Restricted keys with read access are preferred.',
      },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⬙',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    tagline: 'Orders, inventory, customers',
    category: 'commerce',
    authType: 'oauth',
    accentColor: '#95bf47',
    scopes: ['read_orders', 'read_products', 'read_customers', 'read_inventory'],
    requiredEnvVars: ['SHOPIFY_CLIENT_ID', 'SHOPIFY_CLIENT_SECRET'],
    implemented: true,
    glyph: '●',
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    tagline: 'Orders, products, coupons',
    category: 'commerce',
    authType: 'api_key',
    accentColor: '#96588a',
    scopes: [],
    apiKeyFields: [
      { name: 'storeUrl', label: 'Store URL', type: 'text', placeholder: 'https://acme.com' },
      { name: 'consumerKey', label: 'Consumer key', type: 'text', placeholder: 'ck_xxxxxx' },
      { name: 'consumerSecret', label: 'Consumer secret', type: 'password', placeholder: 'cs_xxxxxx' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊛',
  },
  {
    id: 'square',
    name: 'Square',
    tagline: 'Payments, orders, catalog',
    category: 'commerce',
    authType: 'oauth',
    accentColor: '#006aff',
    scopes: ['ITEMS_READ', 'ORDERS_READ', 'PAYMENTS_READ'],
    requiredEnvVars: ['SQUARE_CLIENT_ID', 'SQUARE_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊠',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    tagline: 'Transactions, invoices, payouts',
    category: 'commerce',
    authType: 'api_key',
    accentColor: '#003087',
    scopes: [],
    apiKeyFields: [
      { name: 'clientId', label: 'Client ID', type: 'text' },
      { name: 'clientSecret', label: 'Client secret', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊡',
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    tagline: 'Products, sales, subscribers',
    category: 'commerce',
    authType: 'oauth',
    accentColor: '#ff90e8',
    scopes: [],
    requiredEnvVars: ['GUMROAD_CLIENT_ID', 'GUMROAD_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊜',
  },
  {
    id: 'lemonsqueezy',
    name: 'Lemon Squeezy',
    tagline: 'Subscriptions, licenses, checkouts',
    category: 'commerce',
    authType: 'api_key',
    accentColor: '#ffc233',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', helper: 'Settings → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊝',
  },

  // ── Email Marketing ─────────────────────────────────────────────
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    tagline: 'Lists, campaigns, automations',
    category: 'email_marketing',
    authType: 'oauth',
    accentColor: '#ffe01b',
    scopes: [],
    requiredEnvVars: ['MAILCHIMP_CLIENT_ID', 'MAILCHIMP_CLIENT_SECRET'],
    implemented: true,
    glyph: '✦',
  },
  {
    id: 'convertkit',
    name: 'Kit (ConvertKit)',
    tagline: 'Subscribers, sequences, broadcasts',
    category: 'email_marketing',
    authType: 'api_key',
    accentColor: '#fb6970',
    scopes: [],
    apiKeyFields: [
      { name: 'apiSecret', label: 'API secret', type: 'password', helper: 'Settings → Advanced → API' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '✧',
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    tagline: 'Contacts, automations, deals',
    category: 'email_marketing',
    authType: 'api_key',
    accentColor: '#356ae6',
    scopes: [],
    apiKeyFields: [
      { name: 'accountUrl', label: 'Account URL', type: 'text', placeholder: 'https://acme.api-us1.com' },
      { name: 'apiKey', label: 'API key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '✩',
  },
  {
    id: 'beehiiv',
    name: 'Beehiiv',
    tagline: 'Newsletter subscribers, posts',
    category: 'email_marketing',
    authType: 'api_key',
    accentColor: '#000000',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', helper: 'Settings → Integrations → API' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '✪',
  },
  {
    id: 'resend',
    name: 'Resend',
    tagline: 'Developer-first transactional email',
    category: 'email_marketing',
    authType: 'api_key',
    accentColor: '#000000',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', placeholder: 're_xxxxxxxx' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊹',
  },

  // ── Social Media ────────────────────────────────────────────────
  {
    id: 'twitter',
    name: 'X (Twitter)',
    tagline: 'Posts, followers, analytics',
    category: 'social',
    authType: 'oauth',
    accentColor: '#000000',
    scopes: ['tweet.read', 'users.read', 'offline.access'],
    requiredEnvVars: ['TWITTER_CLIENT_ID', 'TWITTER_CLIENT_SECRET'],
    implemented: true,
    glyph: '𝕏',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    tagline: 'Posts, company pages, analytics',
    category: 'social',
    authType: 'oauth',
    accentColor: '#0a66c2',
    scopes: ['r_liteprofile', 'r_organization_social'],
    requiredEnvVars: ['LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊞',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    tagline: 'Posts, stories, insights',
    category: 'social',
    authType: 'oauth',
    accentColor: '#e1306c',
    scopes: ['instagram_basic', 'instagram_manage_insights'],
    requiredEnvVars: ['META_APP_ID', 'META_APP_SECRET'],
    implemented: true,
    glyph: '⊞',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    tagline: 'Videos, analytics, followers',
    category: 'social',
    authType: 'oauth',
    accentColor: '#000000',
    scopes: ['user.info.basic', 'video.list'],
    requiredEnvVars: ['TIKTOK_CLIENT_KEY', 'TIKTOK_CLIENT_SECRET'],
    implemented: true,
    glyph: '♪',
  },
  {
    id: 'buffer',
    name: 'Buffer',
    tagline: 'Schedule posts across channels',
    category: 'social',
    authType: 'oauth',
    accentColor: '#168eea',
    scopes: [],
    requiredEnvVars: ['BUFFER_CLIENT_ID', 'BUFFER_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊓',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    tagline: 'Channels, videos, analytics',
    category: 'social',
    authType: 'oauth',
    accentColor: '#ff0000',
    scopes: ['https://www.googleapis.com/auth/youtube.readonly', 'https://www.googleapis.com/auth/yt-analytics.readonly'],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '▷',
  },

  // ── Advertising ─────────────────────────────────────────────────
  {
    id: 'meta_ads',
    name: 'Meta Ads',
    tagline: 'Facebook & Instagram ad performance',
    category: 'advertising',
    authType: 'oauth',
    accentColor: '#1877f2',
    scopes: ['ads_read', 'ads_management', 'business_management'],
    requiredEnvVars: ['META_APP_ID', 'META_APP_SECRET'],
    implemented: true,
    glyph: '◐',
  },
  {
    id: 'google_ads',
    name: 'Google Ads',
    tagline: 'Search, Display, YouTube campaigns',
    category: 'advertising',
    authType: 'oauth',
    accentColor: '#4285f4',
    scopes: ['openid', 'email', 'profile', 'https://www.googleapis.com/auth/adwords'],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_ADS_DEVELOPER_TOKEN'],
    implemented: true,
    glyph: '◒',
  },
  {
    id: 'tiktok_ads',
    name: 'TikTok Ads',
    tagline: 'Campaign performance, audiences',
    category: 'advertising',
    authType: 'oauth',
    accentColor: '#000000',
    scopes: [],
    requiredEnvVars: ['TIKTOK_ADS_APP_ID', 'TIKTOK_ADS_SECRET'],
    implemented: true,
    glyph: '♫',
  },
  {
    id: 'linkedin_ads',
    name: 'LinkedIn Ads',
    tagline: 'Sponsored content, lead gen forms',
    category: 'advertising',
    authType: 'oauth',
    accentColor: '#0a66c2',
    scopes: ['r_ads_reporting', 'r_ads'],
    requiredEnvVars: ['LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊟',
  },

  // ── Analytics ───────────────────────────────────────────────────
  {
    id: 'google_analytics',
    name: 'Google Analytics',
    tagline: 'GA4 property metrics',
    category: 'analytics',
    authType: 'oauth',
    accentColor: '#f9ab00',
    scopes: ['openid', 'email', 'profile', 'https://www.googleapis.com/auth/analytics.readonly'],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '◓',
  },
  {
    id: 'google_search_console',
    name: 'Search Console',
    tagline: 'Organic impressions & clicks',
    category: 'analytics',
    authType: 'oauth',
    accentColor: '#4285f4',
    scopes: ['openid', 'email', 'profile', 'https://www.googleapis.com/auth/webmasters.readonly'],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '◔',
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    tagline: 'Events, funnels, retention',
    category: 'analytics',
    authType: 'api_key',
    accentColor: '#7856ff',
    scopes: [],
    apiKeyFields: [
      { name: 'projectToken', label: 'Project token', type: 'text' },
      { name: 'apiSecret', label: 'API secret', type: 'password', helper: 'Project Settings → Management → API Secret' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊚',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    tagline: 'Product analytics, cohorts',
    category: 'analytics',
    authType: 'api_key',
    accentColor: '#1b1f3b',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password' },
      { name: 'secretKey', label: 'Secret key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊛',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    tagline: 'Product analytics, feature flags',
    category: 'analytics',
    authType: 'api_key',
    accentColor: '#f9bd2b',
    scopes: [],
    apiKeyFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'https://app.posthog.com' },
      { name: 'apiKey', label: 'Personal API key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '🦔',
  },
  {
    id: 'plausible',
    name: 'Plausible',
    tagline: 'Privacy-friendly web analytics',
    category: 'analytics',
    authType: 'api_key',
    accentColor: '#5850ec',
    scopes: [],
    apiKeyFields: [
      { name: 'siteId', label: 'Site ID', type: 'text', placeholder: 'example.com' },
      { name: 'apiKey', label: 'API key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊜',
  },
  {
    id: 'segment',
    name: 'Segment',
    tagline: 'Customer data platform, event routing',
    category: 'analytics',
    authType: 'api_key',
    accentColor: '#52bd94',
    scopes: [],
    apiKeyFields: [
      { name: 'writeKey', label: 'Write key', type: 'password', helper: 'Sources → Settings → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊝',
  },

  // ── Design ──────────────────────────────────────────────────────
  {
    id: 'canva',
    name: 'Canva',
    tagline: 'Designs, templates, brand kits',
    category: 'design',
    authType: 'oauth',
    accentColor: '#00c4cc',
    scopes: ['design:read', 'asset:read', 'brand:read'],
    requiredEnvVars: ['CANVA_CLIENT_ID', 'CANVA_CLIENT_SECRET'],
    implemented: true,
    glyph: '◈',
  },
  {
    id: 'miro',
    name: 'Miro',
    tagline: 'Whiteboards, diagrams, workflows',
    category: 'design',
    authType: 'oauth',
    accentColor: '#ffd02f',
    scopes: ['boards:read', 'boards:write'],
    requiredEnvVars: ['MIRO_CLIENT_ID', 'MIRO_CLIENT_SECRET'],
    implemented: true,
    glyph: '◇',
  },
  {
    id: 'adobe_creative_cloud',
    name: 'Adobe Creative Cloud',
    tagline: 'Photoshop, Illustrator, assets',
    category: 'design',
    authType: 'oauth',
    accentColor: '#ff0000',
    scopes: ['openid', 'creative_sdk'],
    requiredEnvVars: ['ADOBE_CLIENT_ID', 'ADOBE_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬘',
  },
  {
    id: 'sketch',
    name: 'Sketch',
    tagline: 'Artboards, symbols, libraries',
    category: 'design',
    authType: 'oauth',
    accentColor: '#fdad00',
    scopes: [],
    requiredEnvVars: ['SKETCH_CLIENT_ID', 'SKETCH_CLIENT_SECRET'],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '◇',
  },

  // ── Cloud Storage ───────────────────────────────────────────────
  {
    id: 'google_drive',
    name: 'Google Drive',
    tagline: 'Files, folders, shared drives',
    category: 'cloud_storage',
    authType: 'oauth',
    accentColor: '#4285f4',
    scopes: ['openid', 'email', 'profile', 'https://www.googleapis.com/auth/drive.readonly'],
    requiredEnvVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    implemented: true,
    glyph: '▲',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    tagline: 'Files, folders, sharing links',
    category: 'cloud_storage',
    authType: 'oauth',
    accentColor: '#0061ff',
    scopes: ['files.metadata.read', 'files.content.read'],
    requiredEnvVars: ['DROPBOX_CLIENT_ID', 'DROPBOX_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬒',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    tagline: 'Files, folders, SharePoint',
    category: 'cloud_storage',
    authType: 'oauth',
    accentColor: '#0078d4',
    scopes: ['Files.Read.All', 'User.Read'],
    requiredEnvVars: ['MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬓',
  },
  {
    id: 'box',
    name: 'Box',
    tagline: 'Files, folders, metadata',
    category: 'cloud_storage',
    authType: 'oauth',
    accentColor: '#0061d5',
    scopes: [],
    requiredEnvVars: ['BOX_CLIENT_ID', 'BOX_CLIENT_SECRET'],
    implemented: true,
    glyph: '⬔',
  },

  // ── Forms ───────────────────────────────────────────────────────
  {
    id: 'typeform',
    name: 'Typeform',
    tagline: 'Forms, surveys, responses',
    category: 'forms',
    authType: 'oauth',
    accentColor: '#262627',
    scopes: ['forms:read', 'responses:read'],
    requiredEnvVars: ['TYPEFORM_CLIENT_ID', 'TYPEFORM_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊞',
  },
  {
    id: 'tally',
    name: 'Tally',
    tagline: 'Forms, submissions, webhooks',
    category: 'forms',
    authType: 'api_key',
    accentColor: '#000000',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', helper: 'Settings → Integrations → API' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⊟',
  },
  {
    id: 'jotform',
    name: 'JotForm',
    tagline: 'Forms, submissions, reports',
    category: 'forms',
    authType: 'api_key',
    accentColor: '#0a1551',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', helper: 'Settings → API' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⊠',
  },
  {
    id: 'surveymonkey',
    name: 'SurveyMonkey',
    tagline: 'Surveys, responses, analysis',
    category: 'forms',
    authType: 'oauth',
    accentColor: '#00bf6f',
    scopes: ['surveys_read', 'responses_read_detail'],
    requiredEnvVars: ['SURVEYMONKEY_CLIENT_ID', 'SURVEYMONKEY_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊡',
  },

  // ── Support ─────────────────────────────────────────────────────
  {
    id: 'zendesk',
    name: 'Zendesk',
    tagline: 'Tickets, contacts, satisfaction',
    category: 'support',
    authType: 'oauth',
    accentColor: '#03363d',
    scopes: ['read', 'tickets:read'],
    requiredEnvVars: ['ZENDESK_CLIENT_ID', 'ZENDESK_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊕',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    tagline: 'Conversations, contacts, articles',
    category: 'support',
    authType: 'oauth',
    accentColor: '#286efa',
    scopes: [],
    requiredEnvVars: ['INTERCOM_CLIENT_ID', 'INTERCOM_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊖',
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    tagline: 'Tickets, contacts, knowledge base',
    category: 'support',
    authType: 'api_key',
    accentColor: '#25c16f',
    scopes: [],
    apiKeyFields: [
      { name: 'domain', label: 'Domain', type: 'text', placeholder: 'acme.freshdesk.com' },
      { name: 'apiKey', label: 'API key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊗',
  },
  {
    id: 'helpscout',
    name: 'Help Scout',
    tagline: 'Mailboxes, conversations, docs',
    category: 'support',
    authType: 'oauth',
    accentColor: '#1292ee',
    scopes: [],
    requiredEnvVars: ['HELPSCOUT_CLIENT_ID', 'HELPSCOUT_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊘',
  },
  {
    id: 'crisp',
    name: 'Crisp',
    tagline: 'Live chat, inbox, knowledge base',
    category: 'support',
    authType: 'api_key',
    accentColor: '#4e82ee',
    scopes: [],
    apiKeyFields: [
      { name: 'websiteId', label: 'Website ID', type: 'text' },
      { name: 'tokenId', label: 'Token ID', type: 'text' },
      { name: 'tokenKey', label: 'Token key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊙',
  },

  // ── Finance ─────────────────────────────────────────────────────
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    tagline: 'Invoices, expenses, reports',
    category: 'finance',
    authType: 'oauth',
    accentColor: '#2ca01c',
    scopes: ['com.intuit.quickbooks.accounting'],
    requiredEnvVars: ['QUICKBOOKS_CLIENT_ID', 'QUICKBOOKS_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊚',
  },
  {
    id: 'xero',
    name: 'Xero',
    tagline: 'Accounting, invoices, bank feeds',
    category: 'finance',
    authType: 'oauth',
    accentColor: '#13b5ea',
    scopes: ['accounting.transactions.read', 'accounting.contacts.read'],
    requiredEnvVars: ['XERO_CLIENT_ID', 'XERO_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊛',
  },
  {
    id: 'freshbooks',
    name: 'FreshBooks',
    tagline: 'Invoicing, expenses, time tracking',
    category: 'finance',
    authType: 'oauth',
    accentColor: '#0075dd',
    scopes: [],
    requiredEnvVars: ['FRESHBOOKS_CLIENT_ID', 'FRESHBOOKS_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊜',
  },
  {
    id: 'wave',
    name: 'Wave',
    tagline: 'Accounting, invoicing, receipts',
    category: 'finance',
    authType: 'oauth',
    accentColor: '#085078',
    scopes: [],
    requiredEnvVars: ['WAVE_CLIENT_ID', 'WAVE_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊝',
  },

  // ── HR ──────────────────────────────────────────────────────────
  {
    id: 'bamboohr',
    name: 'BambooHR',
    tagline: 'Employees, time off, directory',
    category: 'hr',
    authType: 'api_key',
    accentColor: '#73c41d',
    scopes: [],
    apiKeyFields: [
      { name: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'acme' },
      { name: 'apiKey', label: 'API key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊞',
  },
  {
    id: 'gusto',
    name: 'Gusto',
    tagline: 'Payroll, benefits, HR',
    category: 'hr',
    authType: 'oauth',
    accentColor: '#f45d48',
    scopes: ['employees:read', 'payrolls:read'],
    requiredEnvVars: ['GUSTO_CLIENT_ID', 'GUSTO_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊟',
  },
  {
    id: 'rippling',
    name: 'Rippling',
    tagline: 'HR, IT, finance unified platform',
    category: 'hr',
    authType: 'oauth',
    accentColor: '#fedd00',
    scopes: [],
    requiredEnvVars: ['RIPPLING_CLIENT_ID', 'RIPPLING_CLIENT_SECRET'],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⊠',
  },
  {
    id: 'deel',
    name: 'Deel',
    tagline: 'Global payroll, contractors, compliance',
    category: 'hr',
    authType: 'api_key',
    accentColor: '#15357a',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API token', type: 'password', helper: 'Organization Settings → Integrations → API' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊡',
  },

  // ── AI ──────────────────────────────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    tagline: 'GPT, DALL·E, Whisper APIs',
    category: 'ai',
    authType: 'api_key',
    accentColor: '#10a37f',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', placeholder: 'sk-xxxxxx', helper: 'platform.openai.com → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⬡',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    tagline: 'Claude API for advanced reasoning',
    category: 'ai',
    authType: 'api_key',
    accentColor: '#d4a574',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', placeholder: 'sk-ant-xxxxxx', helper: 'console.anthropic.com → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⬢',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    tagline: 'Text-to-speech, voice cloning',
    category: 'ai',
    authType: 'api_key',
    accentColor: '#000000',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password', helper: 'Profile → API Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⬣',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    tagline: 'Open-source ML model hosting',
    category: 'ai',
    authType: 'api_key',
    accentColor: '#000000',
    scopes: [],
    apiKeyFields: [
      { name: 'apiToken', label: 'API token', type: 'password', helper: 'Account Settings → API Tokens' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⬠',
  },

  // ── Automation ──────────────────────────────────────────────────
  {
    id: 'zapier',
    name: 'Zapier',
    tagline: 'Connect 6,000+ apps via Zaps',
    category: 'automation',
    authType: 'api_key',
    accentColor: '#ff4a00',
    scopes: [],
    apiKeyFields: [
      { name: 'webhookUrl', label: 'Webhook URL', type: 'text', placeholder: 'https://hooks.zapier.com/hooks/catch/…', helper: 'Trigger → Webhooks by Zapier → Catch Hook' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⚡',
  },
  {
    id: 'make',
    name: 'Make',
    tagline: 'Visual automation scenarios',
    category: 'automation',
    authType: 'api_key',
    accentColor: '#6d00cc',
    scopes: [],
    apiKeyFields: [
      { name: 'apiToken', label: 'API token', type: 'password', helper: 'Profile → API Tokens' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'us1 or eu1' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⚙',
  },
  {
    id: 'n8n',
    name: 'n8n',
    tagline: 'Self-hosted workflow automation',
    category: 'automation',
    authType: 'api_key',
    accentColor: '#ea4b71',
    scopes: [],
    apiKeyFields: [
      { name: 'baseUrl', label: 'Instance URL', type: 'text', placeholder: 'https://n8n.example.com' },
      { name: 'apiKey', label: 'API key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations
    glyph: '⟐',
  },

  // ── Developer Tools ─────────────────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    tagline: 'Repositories, issues, PRs',
    category: 'devtools',
    authType: 'oauth',
    accentColor: '#24292f',
    scopes: ['repo', 'read:org'],
    requiredEnvVars: ['GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET'],
    implemented: true,
    glyph: '◎',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    tagline: 'Projects, merge requests, CI/CD',
    category: 'devtools',
    authType: 'oauth',
    accentColor: '#fc6d26',
    scopes: ['read_api', 'read_user'],
    requiredEnvVars: ['GITLAB_CLIENT_ID', 'GITLAB_CLIENT_SECRET'],
    implemented: true,
    glyph: '◍',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    tagline: 'Repos, pull requests, pipelines',
    category: 'devtools',
    authType: 'oauth',
    accentColor: '#0052cc',
    scopes: ['repository', 'pullrequest'],
    requiredEnvVars: ['BITBUCKET_CLIENT_ID', 'BITBUCKET_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊜',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    tagline: 'Deployments, projects, domains',
    category: 'devtools',
    authType: 'oauth',
    accentColor: '#000000',
    scopes: [],
    requiredEnvVars: ['VERCEL_CLIENT_ID', 'VERCEL_CLIENT_SECRET'],
    implemented: true,
    glyph: '▲',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    tagline: 'Errors, performance, releases',
    category: 'devtools',
    authType: 'oauth',
    accentColor: '#362d59',
    scopes: ['project:read', 'event:read'],
    requiredEnvVars: ['SENTRY_CLIENT_ID', 'SENTRY_CLIENT_SECRET'],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⊗',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    tagline: 'Metrics, logs, APM dashboards',
    category: 'devtools',
    authType: 'api_key',
    accentColor: '#632ca6',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key', type: 'password' },
      { name: 'appKey', label: 'Application key', type: 'password' },
      { name: 'site', label: 'Site', type: 'text', placeholder: 'datadoghq.com' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊙',
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    tagline: 'Incidents, on-call, escalations',
    category: 'devtools',
    authType: 'api_key',
    accentColor: '#06ac38',
    scopes: [],
    apiKeyFields: [
      { name: 'apiKey', label: 'API key (v2)', type: 'password', helper: 'Integrations → API Access Keys' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊚',
  },

  // ── Database ────────────────────────────────────────────────────
  {
    id: 'supabase',
    name: 'Supabase',
    tagline: 'Database, auth, storage, realtime',
    category: 'database',
    authType: 'api_key',
    accentColor: '#3ecf8e',
    scopes: [],
    apiKeyFields: [
      { name: 'projectUrl', label: 'Project URL', type: 'text', placeholder: 'https://xxxxx.supabase.co' },
      { name: 'serviceKey', label: 'Service role key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊞',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    tagline: 'Firestore, Auth, Cloud Functions',
    category: 'database',
    authType: 'service_account',
    accentColor: '#ffca28',
    scopes: [],
    apiKeyFields: [
      { name: 'serviceAccountJson', label: 'Service account JSON', type: 'password', helper: 'Firebase Console → Project Settings → Service Accounts → Generate New Private Key' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊟',
  },
  {
    id: 'mongodb',
    name: 'MongoDB Atlas',
    tagline: 'Collections, documents, Atlas API',
    category: 'database',
    authType: 'api_key',
    accentColor: '#00ed64',
    scopes: [],
    apiKeyFields: [
      { name: 'publicKey', label: 'Public key', type: 'text' },
      { name: 'privateKey', label: 'Private key', type: 'password' },
      { name: 'groupId', label: 'Project ID', type: 'text' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊠',
  },

  // ── Video ───────────────────────────────────────────────────────
  {
    id: 'loom',
    name: 'Loom',
    tagline: 'Videos, transcripts, embeds',
    category: 'video',
    authType: 'oauth',
    accentColor: '#625df5',
    scopes: [],
    requiredEnvVars: ['LOOM_CLIENT_ID', 'LOOM_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊕',
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    tagline: 'Videos, folders, analytics',
    category: 'video',
    authType: 'oauth',
    accentColor: '#1ab7ea',
    scopes: ['public', 'private'],
    requiredEnvVars: ['VIMEO_CLIENT_ID', 'VIMEO_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊖',
  },
  {
    id: 'mux',
    name: 'Mux',
    tagline: 'Video hosting, streaming, analytics',
    category: 'video',
    authType: 'api_key',
    accentColor: '#fb3ca5',
    scopes: [],
    apiKeyFields: [
      { name: 'tokenId', label: 'Access token ID', type: 'text' },
      { name: 'tokenSecret', label: 'Secret key', type: 'password' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊗',
  },

  // ── Infrastructure ──────────────────────────────────────────────
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    tagline: 'Zones, DNS, analytics',
    category: 'infra',
    authType: 'api_key',
    accentColor: '#f38020',
    scopes: [],
    apiKeyFields: [
      {
        name: 'apiToken',
        label: 'API token',
        type: 'password',
        placeholder: 'Bearer token from Cloudflare dashboard',
        helper: 'My Profile → API Tokens → Create token. Grant Zone:Read + Analytics:Read at minimum.',
      },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '☁',
  },
  {
    id: 'aws',
    name: 'AWS',
    tagline: 'S3, Lambda, CloudWatch',
    category: 'infra',
    authType: 'api_key',
    accentColor: '#ff9900',
    scopes: [],
    apiKeyFields: [
      { name: 'accessKeyId', label: 'Access key ID', type: 'text' },
      { name: 'secretAccessKey', label: 'Secret access key', type: 'password' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1' },
    ],
    requiredEnvVars: [],
    implemented: false, // [TODO] adapter not yet built — see scripts/check-integrations,
    glyph: '⊞',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    tagline: 'Sites, deploys, forms',
    category: 'infra',
    authType: 'oauth',
    accentColor: '#00c7b7',
    scopes: [],
    requiredEnvVars: ['NETLIFY_CLIENT_ID', 'NETLIFY_CLIENT_SECRET'],
    implemented: true,
    glyph: '⊟',
  },
  {
    id: 'fly',
    name: 'Fly.io',
    tagline: 'Apps, machines, volumes',
    category: 'infra',
    authType: 'api_key',
    accentColor: '#7b3fe4',
    scopes: [],
    apiKeyFields: [
      { name: 'apiToken', label: 'API token', type: 'password', helper: 'fly tokens create' },
    ],
    requiredEnvVars: [],
    implemented: true,
    glyph: '⊠',
  },
];

/** Look up a provider by its canonical slug. */
export function findProvider(id: string): IntegrationProviderDef | null {
  return PROVIDERS.find(p => p.id === id) ?? null;
}

/** Filter to providers whose declared env vars are actually set. */
export function hasRequiredEnv(def: IntegrationProviderDef): boolean {
  return def.requiredEnvVars.every(name => Boolean(process.env[name]));
}

/**
 * Summary shape for the /api/integrations/providers endpoint and the
 * provider grid. Keeps the client bundle small: no secrets, no SDKs.
 */
export type ProviderSummary = {
  id: string;
  name: string;
  tagline: string;
  category: IntegrationCategory;
  categoryLabel: string;
  authType: IntegrationAuthType;
  accentColor: string;
  glyph: string;
  implemented: boolean;
  envReady: boolean;
  missingEnvVars: string[];
  apiKeyFields?: IntegrationProviderDef['apiKeyFields'];
};

export function summarizeProvider(def: IntegrationProviderDef): ProviderSummary {
  const missing = def.requiredEnvVars.filter(name => !process.env[name]);
  return {
    id: def.id,
    name: def.name,
    tagline: def.tagline,
    category: def.category,
    categoryLabel: CATEGORY_LABELS[def.category],
    authType: def.authType,
    accentColor: def.accentColor,
    glyph: def.glyph,
    implemented: def.implemented,
    envReady: missing.length === 0,
    missingEnvVars: missing,
    apiKeyFields: def.apiKeyFields,
  };
}
